# Generated by Django 5.2.8 on 2025-11-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('SI_NO', models.IntegerField(max_length=10)),
                ('product_name', models.CharField(max_length=30)),
                ('price', models.DateField(max_length=10)),
                ('category', models.CharField(max_length=20)),
                ('discription', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=10)),
                ('image_url', models.CharField(max_length=15)),
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
