# Generated by Django 5.2.8 on 2025-11-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0002_alter_product_si_no_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
